### ISSUE TITLE
2022年休假日错误

### ISSUE THREAD

**Issue by liaoxycn** [tangyan85/GetHolidays-master#1]
"20220402": 2,"20220424": 2 这两个是法定工作日，好像所有的补班日都是错的

**Comment by tangyan85** [comment]
> "20220402": 2,"20220424": 2 这两个是法定工作日，好像所有的补班日都是错的
这个程序只适用于基金公司，基金公司不补班的，他们跟交易所保持同一个工作日的，如果是其他行业的公司不适用，需要自己该代码
